version: "3.9"

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zoutacms
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zoutacms
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zoutacms"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_dev_data:
